<?php

namespace App\HttpController;

use EasySwoole\Http\AbstractInterface\Controller;
use EasySwoole\Component\Pool\PoolManager;
use App\Utility\Pool\MysqlPool;
use App\Utility\Pool\MysqlObject;

class Base extends Controller
{
    protected $db;

    //构造Mysql协程连接池对象
    protected function onRequest(?string $action): ?bool
    {
        $this->db = PoolManager::getInstance()->getPool(MysqlPool::class)->getObj();
        if (!$this->db instanceof MysqlObject) {
            throw new \Exception('Db Pool is Empty3');
        }
        return true;
    }


    protected function onException(\Throwable $throwable): void
    {
        $this->response()->write($throwable->getMessage());
    }

    protected function afterAction(?string $actionName): void
    {
        PoolManager::getInstance()->getPool(MysqlPool::class)->recycleObj($this->db);
    }

    public function gc()
    {
        parent::gc(); // TODO: Change the autogenerated stub
        /*
         * 因为控制器是对象池模式，因此请重置自定义属性,否则会被下个请求复用。
         */
        $this->db = null;
    }

    public function index()
    {
        //parent::index();
    }


}
